- name: Deploy to VPS via SSH
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: 193.203.160.121
    username: root
    key: ${{ secrets.VPS_SSH_KEY }}
    port: 22
    script: |
      if [ ! -d "/home/docker/demo.thyroidcentre.in/.git" ]; then
        rm -rf /home/docker/demo.thyroidcentre.in
        git clone https://github.com/thyroidcentre/newebsite.git /home/docker/demo.thyroidcentre.in
      else
        cd /home/docker/demo.thyroidcentre.in
        git pull origin main
      fi

      cd /home/docker/demo.thyroidcentre.in

      docker stop demo-flask_web || true
      docker rm demo-flask_web || true
      docker rmi demo-thyroid-web:latest || true

      docker build -t demo-thyroid-web:latest .

      docker run -d --name demo-flask_web -p 6000:6000 demo-thyroid-web:latest
